-- =====================================================
-- BASE DE DONNEES - GESTION DE TRANSPORT
-- =====================================================

DROP TABLE IF EXISTS TRAJETS;
DROP TABLE IF EXISTS BUS;
DROP TABLE IF EXISTS CONDUCTEURS;

-- TABLE BUS
CREATE TABLE BUS (
    ID_BUS          TEXT PRIMARY KEY,
    IMMATRICULATION TEXT UNIQUE NOT NULL,
    MARQUE          TEXT NOT NULL,
    MODELE          TEXT NOT NULL,
    CAPACITE        INTEGER NOT NULL,
    ANNEE_MISE_CIRCULATION INTEGER,
    STATUT          TEXT DEFAULT 'DISPONIBLE',
    DATE_DERNIER_ENTRETIEN TEXT,
    REMARQUES       TEXT
);

-- TABLE CONDUCTEURS
CREATE TABLE CONDUCTEURS (
    ID_CONDUCTEUR   TEXT PRIMARY KEY,
    NOM             TEXT NOT NULL,
    PRENOM          TEXT NOT NULL,
    EMAIL           TEXT UNIQUE,
    TELEPHONE       TEXT NOT NULL,
    ADRESSE         TEXT,
    VILLE           TEXT,
    CODE_POSTAL     TEXT,
    NUMERO_PERMIS   TEXT UNIQUE NOT NULL,
    DATE_EMBAUCHE   TEXT,
    STATUT          TEXT DEFAULT 'ACTIF',
    SALAIRE_BASE    REAL DEFAULT 2000.00
);

-- TABLE TRAJETS
CREATE TABLE TRAJETS (
    ID_TRAJET       TEXT PRIMARY KEY,
    ID_BUS          TEXT,
    ID_CONDUCTEUR   TEXT,
    VILLE_DEPART    TEXT NOT NULL,
    VILLE_ARRIVEE   TEXT NOT NULL,
    DATE_DEPART     TEXT NOT NULL,
    HEURE_DEPART    TEXT NOT NULL,
    DATE_ARRIVEE    TEXT NOT NULL,
    HEURE_ARRIVEE   TEXT NOT NULL,
    DISTANCE_KM     REAL,
    PRIX_PLACE      REAL NOT NULL,
    NB_PLACES_DISPO INTEGER,
    STATUT          TEXT DEFAULT 'PROGRAMME',
    FOREIGN KEY (ID_BUS) REFERENCES BUS(ID_BUS),
    FOREIGN KEY (ID_CONDUCTEUR) REFERENCES CONDUCTEURS(ID_CONDUCTEUR)
);

CREATE INDEX idx_trajets_date ON TRAJETS(DATE_DEPART);
CREATE INDEX idx_bus_statut ON BUS(STATUT);
CREATE INDEX idx_conducteurs_nom ON CONDUCTEURS(NOM);
