-- Requêtes pour l'analyse pédagogique

-- 1. Moyenne par élève
SELECT E.ID, E.NOM, E.PRENOM, ROUND(AVG(N.VALEUR), 2) AS MOYENNE
FROM ETUDIANT E
LEFT JOIN NOTE N ON E.ID = N.ID_ETUDIANT
GROUP BY E.ID, E.NOM, E.PRENOM
ORDER BY MOYENNE DESC;

-- 2. Meilleurs élèves (moyenne > 15)
SELECT E.ID, E.NOM, E.PRENOM, ROUND(AVG(N.VALEUR), 2) AS MOYENNE
FROM ETUDIANT E
JOIN NOTE N ON E.ID = N.ID_ETUDIANT
GROUP BY E.ID, E.NOM, E.PRENOM
HAVING AVG(N.VALEUR) > 15;

-- 3. Moyenne par matière
SELECT C.ID, C.NOM_COURS, ROUND(AVG(N.VALEUR), 2) AS MOYENNE_CLASSE
FROM COURS C
LEFT JOIN NOTE N ON C.ID = N.ID_COURS
GROUP BY C.ID, C.NOM_COURS
ORDER BY MOYENNE_CLASSE DESC;

-- 4. Élèves en difficulté (moyenne < 10)
SELECT E.ID, E.NOM, E.PRENOM, ROUND(AVG(N.VALEUR), 2) AS MOYENNE
FROM ETUDIANT E
JOIN NOTE N ON E.ID = N.ID_ETUDIANT
GROUP BY E.ID, E.NOM, E.PRENOM
HAVING AVG(N.VALEUR) < 10;

-- 5. Distribution des mentions
SELECT 
    MENTION,
    COUNT(*) AS NOMBRE
FROM EVALUATION
GROUP BY MENTION
ORDER BY MENTION;
