-- Création table DB2
CREATE TABLE VOTREID.COMTAB
  (COMNUM CHAR(6)   NOT NULL,
   COMNOM VARCHAR(30) NOT NULL,
   COMSOL DECIMAL(9,2) NOT NULL);

-- Données de test
INSERT INTO VOTREID.COMTAB VALUES('100001', 'Jean Dupont', 1500.00);
INSERT INTO VOTREID.COMTAB VALUES('100002', 'Marie Curie', 2350.75);
INSERT INTO VOTREID.COMTAB VALUES('100003', 'Albert Einstein', 899.99);

-- Autorisations
GRANT SELECT ON VOTREID.COMTAB TO PUBLIC;
