INSERT INTO EMPLOYEE VALUES
(1,'JEAN DUPONT','IT',2500);

INSERT INTO EMPLOYEE VALUES
(2,'MARIE MARTIN','HR',3200);

INSERT INTO EMPLOYEE VALUES
(3,'PAUL RAKOTO','DEV',4100);

INSERT INTO EMPLOYEE VALUES
(4,'ALICE DURAND','FINANCE',3800);

INSERT INTO EMPLOYEE VALUES
(5,'PAUL RABE','DEV',5000);