SELECT D.DEPTNAME,
       MAX(E.SALARY + COALESCE(E.BONUS, 0) + COALESCE(E.COMM, 0)) AS MAX_COMPENSATION
FROM ibmuser.dept D, ibmuser.emp E
WHERE D.DEPTNO = E.WORKDEPT
GROUP BY D.DEPTNAME
ORDER BY D.DEPTNAME;