CREATE DATABASE APPDB;

CREATE TABLESPACE APPTS
    IN APPDB;

CREATE TABLE APP.CLIENTS
(
    ID INTEGER NOT NULL,
    NOM VARCHAR(30),
    PRENOM VARCHAR(30),
    VILLE VARCHAR(30),
    AGE INTEGER,
    PRIMARY KEY(ID)
)
IN APPDB.APPTS;