SELECT ACCOUNT_ID, CLIENT_NAME, BALANCE, CREATED_DATE
  FROM Z74830.ACCOUNT;


-- CREATE TABLE Z74830.ACCOUNT
-- (
--     ACCOUNT_ID     CHAR(10)      NOT NULL,
--     CLIENT_NAME    VARCHAR(50),
--     BALANCE        DECIMAL(12,2),
--     CREATED_DATE   DATE,
--     PRIMARY KEY (ACCOUNT_ID)
-- ) IN DATABASE Z74830;